homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml

alarm_control_panel: !include_dir_list alarms

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: https://home.chingr.com
  api_password: !secret http_api_password

device_tracker: !include_dir_list device_trackers

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
#   ignore:
#     - harmony

stream:

blink:
  username: !secret blink_username
  password: !secret blink_password

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

google_assistant:
  project_id: home-automation-chingr
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light

# Enables support for tracking state changes over time
history:

ifttt:
  key: !secret ifttt_key

konnected: !include konnected.yaml

camera:
  - platform: mjpeg
    mjpeg_url: http://192.168.86.49/axis-cgi/mjpg/video.cgi
    still_image_url: http://192.168.86.49/cgi/jpg/image.cgi
    name: Motorola MBP85CONNECT
  - platform: generic
    name: luna
    still_image_url: !secret wyze_cam_snapshot_luna
    stream_source: !secret wyze_cam_rtsp_luna
  - platform: generic
    name: titan
    still_image_url: !secret wyze_cam_snapshot_titan
    stream_source: !secret wyze_cam_rtsp_titan
  - platform: generic
    name: basement
    still_image_url: !secret wyze_cam_snapshot_basement
    stream_source: !secret wyze_cam_rtsp_basement
  - platform: generic
    name: playroom
    still_image_url: !secret wyze_cam_snapshot_playroom
    stream_source: !secret wyze_cam_rtsp_playroom

recorder:
  purge_keep_days: 5
  db_url: !secret recorder_database

remote:
  - platform: harmony
    name: Theater
    host: 192.168.86.29

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# View all events in a logbook
logbook:

# Track the sun
sun:

# Binary Sensors
binary_sensor: !include_dir_list binary_sensors

# Sensors
sensor: !include_dir_list sensors

# Switches
#switch: !include_dir_list switches

person:
  - name: Jeff
    id: jeff
    user_id: 1763d5d8034e41f8aa54edb213c87e28
    device_trackers:
      - device_tracker.jeff_nmap
      - device_tracker.ching_pixel2xl
  - name: Diana
    id: diana
    device_trackers:
      - device_tracker.diana_nmap
  - name: Stan
    id: stan
    device_trackers:
      - device_tracker.stan_nmap
  - name: Elise
    id: elise
    device_trackers:
      - device_tracker.elise_nmap
  - name: Frankie
    id: frankie
    device_trackers:
      - device_tracker.frankie_nmap
  - name: ManYing
    id: manying
    device_trackers:
      - device_tracker.manying_nmap
  - name: Rachelle
    id: rachelle
    device_trackers:
      - device_tracker.rachelle_nmap1
      - device_tracker.racheele_nmap2
  - name: Edward
    id: edward
    device_trackers:
      - device_tracker.edward_nmap
  - name: Gloria
    id: gloria
    device_trackers:
      - device_tracker.gloria_nmap

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# MQTT config
mqtt:
  broker: 192.168.86.61
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: ha
  discovery: true
  discovery_prefix: smartthings

notify:
  - platform: twilio_sms
    name: Twilio SMS
    from_number: +12062020922
  - platform: html5
    name: Jeff's Phone
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

google_domains:
  domain: home.chingr.com
  username: !secret google_domains_username
  password: !secret google_domains_password
  timeout: 60

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 1
  platform: smart_life

twilio:
  account_sid: !secret twilio_account_sid
  auth_token: !secret twilio_auth_token

owntracks:
  max_gps_accuracy: 200
  waypoints: true
  mqtt_topic: "owntracks/#"

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

lovelace:
  mode: yaml
# usps:
#   username: !secret usps_username
#   password: !secret usps_password

logger:
  default: info
  logs:
    locationsharinglib: debug

influxdb:
  host: 192.168.86.61
  port: 8086
  database: !secret influxdb_database
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

zone: !include zones.yaml
input_select: !include inputs.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include_dir_list scenes