title: My Awesome Home
views:
  - title: Security
    icon: mdi:security
    cards:
      - type: alarm-panel
        entity: alarm_control_panel.home_alarm
      - type: glance
        entities:
          - binary_sensor.garage_door
          - binary_sensor.front_door
          - binary_sensor.basement_door
      - type: picture-glance
        title: Living room
        entities:
          - switch.entryway_switch
        camera_image: camera.motorola_mbp85connect
      - type: picture-glance
        title: Front Door
        entities:
          - switch.front_door_switch
          - binary_sensor.front_door
          - binary_sensor.front_door_camera_motion_detected
          - binary_sensor.front_door_camera_online
          - binary_sensor.front_door_camera_person_detected
          - binary_sensor.front_door_camera_sound_detected
        camera_image: camera.front_door
    # View tab title.
  - title: Home
    icon: mdi:home
    cards:
      - type: entity-filter
        entities:
          - binary_sensor.jeff
          - binary_sensor.diana
          - binary_sensor.frankie
          - binary_sensor.manying
          - binary_sensor.stan
          - binary_sensor.elise
        state_filter:
          - "on"
        show_empty: false
        card:
          title: Who's Home?
          type: glance
          show_name: false
          show_state: false
      - type: weather-forecast
        entity: weather.dark_sky
      - type: entities
        entities:
          - entity: sensor.recycling_or_compost
          - entity: sensor.next_garbage_day
          - entity: sensor.fedex
            name: Fedex
          - entity: sensor.ups
            name: UPS
  - title: Kitchen
    icon: mdi:food-fork-drink
    cards:
      - type: picture-glance
        title: Kitchen
        image: /local/kitchen.jpg
        entities:
          - switch.kitchen_island_switch
          - switch.kitchen_light_switch
          - media_player.kitchen
          - media_player.kitchen_display

      - type: custom:mini-media-player
        entity: media_player.kitchen
        artwork_border: true
        show_source: true
        show_tts: true

      - type: custom:mini-media-player
        entity: media_player.kitchen_display
        artwork_border: true
        show_source: true
        show_tts: true

      - type: entities
        name: Kitchen
        entities:
          - binary_sensor.dining_motion
          - sensor.dining_temperature
          - sensor.dining_humidity
          - sensor.dining_illuminance
          - sensor.dining_multisensor_battery
          - binary_sensor.family_motion
          - sensor.family_temperature
          - sensor.family_humidity
          - sensor.family_illuminance
          - sensor.family_multisensor_battery
      - type: custom:monster-card
        card:
          type: entities
          title: Things that are broken
        filter:
          include:
            - state: "unknown"
          exclude:
            - entity_id: group.*
      - type: custom:monster-card
        show_empty: false
        card:
          type: glance
          title: Low Battery Devices
        filter:
          include:
            - entity_id: "*battery_level*"
              state: '< 25'
            - attributes:
                battery: '< 25'
            - attributes:
                battery_level: '< 25'
  - title: Network
    icon: mdi:ip-network
    cards:
      - type: entities
        title: WiFi
        entities:
          - sensor.google_wifi_current_version
          - sensor.google_wifi_last_restart
          - sensor.google_wifi_local_ip
          - sensor.google_wifi_new_version
          - sensor.google_wifi_status
          - sensor.google_wifi_uptime
      - type: entities
        title: Synology
        entities:
          - sensor.cpu_load_total
          - sensor.memory_usage_real
          - sensor.network_down
          - sensor.network_up
          - sensor.status_sda
          - sensor.status_sdb
          - sensor.total_size_volume_1
          - sensor.used_space_volume_1

resources:
  - url: /local/monster-card.js?v=1
    type: js
  - url: /local/slider-entity-row.js?v=1
    type: js
  - url: /local/mini-media-player-bundle.js?v=0.9.5
    type: module









