title: My Awesome Home
views: !include_dir_list ui-lovelace/

resources:
  - url: /local/monster-card.js?v=1
    type: js
  - url: /local/slider-entity-row.js?v=1
    type: js
  - url: /local/mini-media-player-bundle.js?v=1.0.4
    type: module
  - url: /local/mini-graph-card-bundle.js?v=0.4.2
    type: module
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: /local/custom_ui/calendar-card/calendar-card.js?v=1.0.1
    type: module







